### ISSUE TITLE
Transaction pending for more than 2 hours

### ISSUE THREAD

**Issue by MattAlgoworld** [AlgoWorldNFT/algoworld-explorer#14]
An influence transaction has been stuck for 2 hours so I'm wondering if the worker is running correctly (asset index: 576002647)

**Comment by aorumbayev** [comment]
@MattAlgoworld  thanks for reporting will take a look in couple hours. If possible please append user,s deposit txn id

**Comment by aorumbayev** [comment]
Addressed on workers repo, closing issue
